version: '3.8'
services:
  db:
    build: .
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./chembl33-pg-db:/var/lib/postgresql/data


